package com.sensorsdata.automation.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sensorsdata.automation.greendao.TestCase;

import com.sensorsdata.automation.greendao.TestCaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testCaseDaoConfig;

    private final TestCaseDao testCaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testCaseDaoConfig = daoConfigMap.get(TestCaseDao.class).clone();
        testCaseDaoConfig.initIdentityScope(type);

        testCaseDao = new TestCaseDao(testCaseDaoConfig, this);

        registerDao(TestCase.class, testCaseDao);
    }
    
    public void clear() {
        testCaseDaoConfig.clearIdentityScope();
    }

    public TestCaseDao getTestCaseDao() {
        return testCaseDao;
    }

}
